---
- name: Configurer le fuseau horaire en utilisant une variable Jinja2
  hosts: all
  become: yes
  tasks:
    
    # 1. Installer tzdata (Pré-requis)
    # Cette étape garantit que le chemin de la zone est disponible
    - name: Installer le paquet tzdata (base de données des fuseaux horaires)
      ansible.builtin.apk:
        name: tzdata
        state: present
        update_cache: yes
      tags:
        - packages
        
    # 2. Définir le fuseau horaire avec la variable Jinja2
    - name: Créer le lien symbolique /etc/localtime avec la variable {{ system_timezone }}
      ansible.builtin.file:
        # Le chemin source est construit avec la variable Jinja2
        src: "/usr/share/zoneinfo/{{ system_timezone }}"
        dest: /etc/localtime
        state: link
      tags:
        - timezone