---
- name: Configuration de base robuste pour Alpine Linux (Fuseau Horaire et Locale)
  hosts: all
  become: yes
  tasks:

    # 1. Mise à jour du cache APK (résout l'erreur "no such package")
    - name: Mettre à jour le cache du gestionnaire de paquets APK
      ansible.builtin.apk:
        update_cache: yes
      tags:
        - cache

    # 2. Installation de tzdata (résout l'erreur "timezone not available")
    - name: Installer le paquet tzdata (base de données des fuseaux horaires)
      ansible.builtin.apk:
        name: tzdata
        state: present
      tags:
        - packages

    # 3. CORRECTION DU FUSEAU HORAIRE
    # Remplace l'ancien module 'timezone' par la méthode Alpine (lien symbolique)
    - name: Définir le fuseau horaire (Europe/Paris) via lien symbolique
      ansible.builtin.file:
        # Source : le fichier du fuseau horaire après l'installation de tzdata
        src: /usr/share/zoneinfo/Europe/Paris
        # Destination : l'emplacement standard du fuseau horaire système
        dest: /etc/localtime
        state: link # Crée un lien symbolique
      tags:
        - timezone

    # 4. Configuration de la locale (Utilisation du profil système)
    - name: Définir la locale système par défaut (fr_FR.UTF-8)
      ansible.builtin.lineinfile:
        path: /etc/profile # Définit la variable au niveau global
        line: 'export LANG="fr_FR.UTF-8"'
        regexp: '^export LANG='
        state: present
        create: yes
      tags:
        - locale